### ISSUE TITLE
Bug: Location Field in Listed Entries Display as "[object Object]"

### ISSUE THREAD

**Issue by jbcoder** [aheinze/cockpit#402]
So, I've added in a location field in and filled out an entry with a location. However, once I saved it, the location field in the entry doesn't list the location or even the coordinates. It only says `[object Object]`.
![screen shot 2016-03-25 at 16 04 08](https://cloud.githubusercontent.com/assets/1719239/14055947/5545273e-f2a3-11e5-9b51-7e9059038f56.png)

**Comment by aheinze** [comment]
Thanks, I will work on a solution, where an object doesn't support .toString()

**Comment by piotr-cz** [comment]
After #388 locations address is being saved in database (unless user has placed the marker manually using mouse) so we should show that one or an empty string.

**Comment by jbcoder** [comment]
In my case I had typed in a location and selected it from the auto suggestions list. I never interacted with the map directly. (if that helps at all)

**Comment by piotr-cz** [comment]
This has been fixed by @aheinze by using JSON.stringify on object.
I'd prefer showing just a geolocated address, but stringified object doesn't look bad either.

**Problem**
![patch-before](https://cloud.githubusercontent.com/assets/612953/14170883/3e2d5e22-f730-11e5-98db-751016a7421d.png)

**Fix #403**
![patch-piotr](https://cloud.githubusercontent.com/assets/612953/14170904/54f8cb28-f730-11e5-9978-2c3c14a63775.png)

**Fix https://github.com/aheinze/cockpit/commit/1a9d10f9794aaceeefd41f1cdef4ddcb0341c351**
![patch-aheinze](https://cloud.githubusercontent.com/assets/612953/14170891/4b3742a4-f730-11e5-902c-6342d208df2a.png)
